development:
  adapter: postgresql
  database: ccds_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: ccds_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: ccds_production
  pool: 5
  timeout: 5000
